{% set name = "pyproject-local-kernel" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproject_local_kernel-{{ version }}.tar.gz
  sha256: 01e9f38e1af8e1adbda14c69c36845b4a2296880b8360d3e4d70add63ad093e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - jupyter_client >=8.6.3
    - tomli >=2.0.1

test:
  imports:
    - pyproject_local_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluss/pyproject-local-kernel
  summary: Python Jupyter kernel using project/environment manangers like Rye, Uv, PDM, Poetry, Hatch etc.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - renan-r-santos
