{% set name = "pyproject-local-kernel" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproject_local_kernel-{{ version }}.tar.gz
  sha256: a983a370a4c8b29acfbcc4ccda22d13215c97f24e2b51d980830fa7d5d37fcc5

build:
  noarch: python
  entry_points:
    - pyproject_local_kernel = pyproject_local_kernel.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_client >=8.6.3
    - tomli >=2.0.1
    - traitlets >=5.14.3

test:
  imports:
    - pyproject_local_kernel
  commands:
    - pip check
    - pyproject_local_kernel --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bluss/pyproject-local-kernel
  summary: Python Jupyter kernel using project/environment manangers like Rye, Uv, PDM, Poetry, Hatch etc.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - renan-r-santos
