{% set name = "pyproject-local-kernel" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproject_local_kernel-{{ version }}.tar.gz
  sha256: 7ae2b4a8caea45de457e023fa490ffc955e7d033fe7f5c17bea23b215fba4c1a

build:
  noarch: python
  entry_points:
    - pyproject_local_kernel = pyproject_local_kernel.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - jupyter_client >=8.6.3
    - tomli >=2.0.1
    - traitlets >=5.14.3

test:
  imports:
    - pyproject_local_kernel
  commands:
    - pip check
    - pyproject_local_kernel --help
  requires:
    - pip

about:
  home: https://github.com/bluss/pyproject-local-kernel
  summary: Python Jupyter kernel using project/environment manangers like Rye, Uv, PDM, Poetry, Hatch etc.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - renan-r-santos
