{% set name = "pyproject-local-kernel" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproject_local_kernel-{{ version }}.tar.gz
  sha256: 7f70c50b5f61ab67b30da7d000a1e900c02e6228d2797a1e8b9d095af7644eb9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - tomli >=2.0.1

test:
  imports:
    - pyproject_local_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluss/pyproject-local-kernel
  summary: Python Jupyter kernel using project/environment manangers like Rye, Uv, PDM, Poetry, Hatch etc.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - renan-r-santos
